#!/usr/bin/env python3
"""
extract-plan-items.py — parse a PRD markdown file and emit a skeleton
traceability table with blank Status / Implementation Location columns
for quality-guardian to fill in.

Usage:
    python3 scripts/extract-plan-items.py path/to/plan.md
    python3 scripts/extract-plan-items.py path/to/plan.md --format=markdown
    python3 scripts/extract-plan-items.py path/to/plan.md --include-nongoals

Output is written to stdout. Redirect to a file:
    python3 scripts/extract-plan-items.py tasks/prd.md > skeleton.md

Extraction heuristics:
    - User stories: lines matching "As a/an <role>, I want <action> [so that <outcome>]"
    - Acceptance criteria: bullet lines under a heading that contains "acceptance criteria"
    - Numbered requirements: top-level ordered-list items under a heading that contains
      "requirements" or "functional requirements"
    - Task checklist items: "- [ ]" or "- [x]" bullets
    - Non-goals: bullets under a heading that contains "non-goals" or "out of scope"

No external dependencies. Python 3.8+.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


@dataclass
class PlanItem:
    kind: str           # "US" | "AC" | "REQ" | "T" | "NG"
    ident: str          # e.g. "US-1", "AC-2.3"
    text: str
    parent: Optional[str] = None


USER_STORY_RE = re.compile(
    r"^\s*(?:[-*]\s+)?As an? (?P<role>[^,]+),\s*I want\s+(?P<action>.+?)(?:\s+so that\s+(?P<outcome>.+))?\s*\.?$",
    re.IGNORECASE,
)
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
BULLET_RE = re.compile(r"^\s*[-*]\s+(.*)$")
NUMBERED_RE = re.compile(r"^\s*(\d+)[\.\)]\s+(.*)$")
CHECKLIST_RE = re.compile(r"^\s*[-*]\s+\[[ xX]\]\s+(.*)$")

HEADING_HINTS = {
    "acceptance": "AC",
    "requirement": "REQ",
    "functional requirement": "REQ",
    "task": "T",
    "non-goal": "NG",
    "non goals": "NG",
    "out of scope": "NG",
    "user stor": "US",
}


def classify_heading(title: str) -> Optional[str]:
    t = title.lower()
    for hint, kind in HEADING_HINTS.items():
        if hint in t:
            return kind
    return None


def parse(text: str, include_nongoals: bool) -> List[PlanItem]:
    items: List[PlanItem] = []
    current_kind: Optional[str] = None
    current_story: Optional[str] = None
    us_counter = 0
    ac_counter = 0
    req_counter = 0
    task_counter = 0
    ng_counter = 0

    lines = text.splitlines()
    for raw in lines:
        heading = HEADING_RE.match(raw)
        if heading:
            title = heading.group(2)
            kind = classify_heading(title)
            current_kind = kind
            # reset local AC counter whenever we enter a new section
            ac_counter = 0
            continue

        # 1. User stories — match anywhere, they follow a fixed shape
        us_match = USER_STORY_RE.match(raw.strip("-* ").rstrip())
        if us_match:
            us_counter += 1
            ident = f"US-{us_counter}"
            role = us_match.group("role").strip()
            action = us_match.group("action").strip()
            outcome = (us_match.group("outcome") or "").strip()
            story = f"As a {role}, I want {action}" + (f" so that {outcome}" if outcome else "")
            items.append(PlanItem("US", ident, story))
            current_story = ident
            continue

        # 2. Checklist items
        chk = CHECKLIST_RE.match(raw)
        if chk:
            task_counter += 1
            items.append(PlanItem("T", f"T-{task_counter}", chk.group(1).strip()))
            continue

        # 3. Bulleted items inside known sections
        b = BULLET_RE.match(raw)
        if b and current_kind == "AC":
            ac_counter += 1
            parent = current_story or "AC"
            ident = f"{parent}-AC-{ac_counter}" if current_story else f"AC-{ac_counter}"
            items.append(PlanItem("AC", ident, b.group(1).strip(), parent=current_story))
            continue
        if b and current_kind == "NG" and include_nongoals:
            ng_counter += 1
            items.append(PlanItem("NG", f"NG-{ng_counter}", b.group(1).strip()))
            continue

        # 4. Numbered requirements
        n = NUMBERED_RE.match(raw)
        if n and current_kind == "REQ":
            req_counter += 1
            items.append(PlanItem("REQ", f"REQ-{req_counter}", n.group(2).strip()))
            continue

    return items


def emit_markdown(items: List[PlanItem]) -> str:
    if not items:
        return "_No plan items extracted. Review the plan manually._\n"

    out = [
        "# Plan Item Traceability (skeleton)",
        "",
        "Generated by `scripts/extract-plan-items.py`. Fill in Status and Implementation Location.",
        "",
        "| ID | Plan Requirement | Status | Implementation Location | Notes |",
        "|---|---|---|---|---|",
    ]
    for item in items:
        text = item.text.replace("|", "\\|")
        out.append(f"| {item.ident} | {text} |  |  |  |")
    out.append("")
    return "\n".join(out)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("plan", type=Path, help="path to the plan markdown file")
    parser.add_argument(
        "--format",
        choices=["markdown"],
        default="markdown",
        help="output format (default: markdown)",
    )
    parser.add_argument(
        "--include-nongoals",
        action="store_true",
        help="also emit rows for items under a Non-Goals heading (default: on for completeness)",
        default=True,
    )
    parser.add_argument(
        "--no-nongoals",
        action="store_false",
        dest="include_nongoals",
        help="exclude Non-Goals rows",
    )
    args = parser.parse_args(argv)

    if not args.plan.exists():
        print(f"error: plan file not found: {args.plan}", file=sys.stderr)
        return 2

    text = args.plan.read_text(encoding="utf-8")
    items = parse(text, include_nongoals=args.include_nongoals)

    if args.format == "markdown":
        sys.stdout.write(emit_markdown(items))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
